#!/bin/sh
#
# Starts sld_hub_driver driver
#

start() {
	echo -n "Starting sld_hub_driver driver: "
	insmod /lib/modules/altera_sld_hub_driver.ko
	echo "OK"
}
stop() {
	echo -n "Stopping sld_hub_driver driver: "
	rmmod altera_sld_hub_driver.ko
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

